### ISSUE TITLE
`ondevice daemon` fails with python-daemon==1.5.5

### ISSUE THREAD

**Issue by mreithub** [ondevice/ondevice-client#21]
For python2, the currently recommended version of python-daemon is 1.5.5 (the current version uses features that are incompatible to python2.6).

when running `ondevice daemon` with `python-daemon==1.5.5` installed, the following exception is thrown:

```
Traceback (most recent call last):
  File "/usr/local/bin/ondevice", line 9, in <module>
    load_entry_point('ondevice==0.2.3', 'console_scripts', 'ondevice')()
  File "/usr/local/lib/python2.6/dist-packages/ondevice/__init__.py", line 10, in _main
    return main(sys.argv[1:])
  File "/usr/local/lib/python2.6/dist-packages/ondevice/__init__.py", line 25, in main
    return commands.run(cmd, *args, **opts)
  File "/usr/local/lib/python2.6/dist-packages/ondevice/commands/__init__.py", line 14, in run
    return cmd.run(*args, **opts)
  File "/usr/local/lib/python2.6/dist-packages/ondevice/commands/daemon.py", line 18, in run
    with daemon.DaemonContext():
AttributeError: 'module' object has no attribute 'DaemonContext'
```

possible solutions:

- figure out when `DaemonContext` was introduced to python-daemon
- fix `ondevice daemon` to use the older python-daemon API
- find out where to report `python-daemon` bugs. The [alioth][1] homepage (linked to from pypi) lists 1.5.5 as the last version which seems kinda out of date...

[1]: https://alioth.debian.org/projects/python-daemon/

**Comment by mreithub** [comment]
Turns out it was a name clash between the `daemon.py` command.
I'll add a `_cmd` suffix to the command modules...

**Comment by mreithub** [comment]
btw: `python-daemon==1.5.5` seems to be pretty much the most recent version that's compatible with python 2.6, so we'll have to stick with that for now.
